name: Node.js CI

on: pull_request

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '22.x'
                  cache: 'npm'
            - run: npm ci
            - run: npm run format
            - run: npm run lint
            - run: touch result.json
            - run: npm test
            - name: Eslint check
              uses: krizzu/eslint-check-action@v1.1.0
              with:
                  ghToken: ${{ secrets.GITHUB_TOKE }}
                  eslintConfig: eslint.config.js
