name: Node.js CI

on: pull_request

permissions:
    contents: read
    pull-requests: write
    actions: read
    checks: write

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '22.x'
                  cache: 'npm'
            - run: npm ci
            - run: npm run format
            - run: npm run lint
            - run: touch result.json
            - run: npm run test-ci
            - name: Publish Test Report
              uses: dorny/test-reporter@v1
              if: success() || failure()
              with:
                  name: Jest Test Results
                  path: test-results/junit.xml
                  reporter: jest-junit
                  fail-on-error: true
                  list-suites: 'all'
                  list-tests: 'all'
                  max-annotations: 10
                  output-annotations: 'true'
                  comment-mode: always
