name: Node.js CI

on: pull_request

permissions:
    contents: read
    pull-requests: write
    actions: read
    checks: write

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '22.x'
                  cache: 'npm'
            - run: npm ci
            - run: npm run format
            - run: npm run lint
            - run: touch result.json
            - run: npm run test-ci
            - name: Publish test report
              uses: dorny/test-reporter@v1.9.1
              if: ${{ !cancelled() }}
              with:
                  name: Testing Results
                  path: ./junit.xml
                  reporter: jest-junit
                  list-suites: 'all'
                  list-tests: 'all'
                  max-annotations: 10
