name: simple worflow using checkout 

on:
  push: 
   branches: master

jobs: 
  main: 
    runs-on: ubuntu-latest
    defaults:
      run: 
        work-directory: ./scripts
    steps:
      - name: checkout the repo
        usese: actions/checkout@v4
      - name: start
        run: ./start.sh
      - name: example
        run: ./example.sh
