name: simple worflow using checkout 

on:
  push:
    branches: master

jobs: 
  main: 
    runs-on: ubuntu-latest
    defaults:
      run: 
        working-directory: ./scripts
    steps:
      - name: checkout the repo
        uses: actions/checkout@v4
      - name: start
        run: ./start.sh
      - name: example
        run: ./example.sh
